permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required to checkout the code from the repo
name: openapi-lucid basic
# on:
#     push:
#         branches:
#             - master
on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'     
        required: true
        default: 'ap-south-1'
        options: ['ap-south-1']
        type: choice
      filename:
        description: 'file name of lucid document ?'     
        required: true
        default: 'basic-apigateway-lambda'
        type: string
      filefolder:
        description: 'file folder of lucid ?'     
        required: true
        default: 'lucid-files'
        type: string
      fileformat:
        description: 'file format ?'     
        required: true
        default: 'csv'
        options: ['csv']
        type: choice
      preference:
        description: 'file format ?'     
        required: true
        default: 'terraform'
        options: ['terraform', 'serverless']
        type: choice

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
            matrix:
                node-version: [16.x]
      steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Install python
        run: |
          cd ./openapi-lucid
          # Upgrading python to 3.9
          echo "installing pip"
          sudo apt-get install python3
          sudo apt install python3-pip
          pip install --upgrade pip
          pip3.10 install aiohttp
          pip3.10 install --ignore-installed pyOpenSSL==22.0.0
          pip3.10 install openai
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          python3  main-serverless.py -o ${{ github.event.inputs.filename }}-${{ github.event.inputs.preference }} -d ${{ github.event.inputs.filename }} -p ${{ github.event.inputs.preference }}
          cd ../
      - name: Set up Git user
        run: |
          git config --global user.name "prabhakarit"
          git config --global user.email "prabhakar.borah@gmail.com"
      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Auto-commit: lucid chart intgeration"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}